apps/jobs/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('<int:id>', views.job_view, name='job'),
    path('new', views.new_job, name='new_job'),
    path('<int:job_id>/apply', views.apply_for_job, name='apply_for_job'),
    path('<int:job_id>/dashboard', views.job_dashboard, name='job_dashboard'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('', include('apps.profiles.urls')),
    path('jobs/', include('apps.jobs.urls')),
]

apps/jobs/models.py
from django.contrib.auth.models import User
from django.db import models


class Job(models.Model):
    """ Model that represent job in database """

    title = models.CharField(max_length=200)
    description = models.TextField()
    details = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    employer = models.ForeignKey(User, related_name='jobs', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Application(models.Model):
    """ Model that represent user application for a job in database """

    job = models.ForeignKey(Job, related_name='applications', on_delete=models.CASCADE)
    content = models.TextField()
    experience = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    applicant = models.ForeignKey(User, related_name='applications', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.applicant.username} - {self.job.title}'

apps/jobs/forms.py
from django import forms

from . models import Job, Application


class NewJobForm(forms.ModelForm):
    """ Form for creating new job """

    class Meta:
        model = Job
        fields = ['title', 'description', 'details']

class ApplicationForm(forms.ModelForm):
    """ Form for applying for a job """

    class Meta:
        model = Application
        fields = ['content', 'experience']

apps/jobs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from apps.profiles.utilities import create_notification
from . models import Job
from . forms import NewJobForm, ApplicationForm


def job_view(request, id):
    job = get_object_or_404(Job, pk=id)

    context = { 'job': job }
    return render(request, 'jobs/job.html', context)

@login_required
def new_job(request):
    if request.method == 'POST':
        form = NewJobForm(request.POST)
        if form.is_valid():
            job = form.save(commit=False)
            job.employer = request.user
            job.save()

            return redirect('dashboard')
    else:
        form = NewJobForm()

    context = { 'form': form }
    return render(request, 'jobs/new_job.html', context)

@login_required
def apply_for_job(request, job_id):
    job = Job.objects.get(pk=job_id)

    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            app = form.save(commit=False)
            app.job = job
            app.applicant = request.user
            app.save()

            create_notification(request, job.employer, 'application', app.id)

            return redirect('dashboard')
    else:
        form = ApplicationForm()

    context = {
        'form': form,
        'job': job,
    }
    return render(request, 'jobs/apply_for_job.html', context)

@login_required
def job_dashboard(request, job_id):
    job = get_object_or_404(Job, pk=job_id, employer=request.user)

    context = { 'job': job }
    return render(request, 'jobs/job_dashboard.html', context)

templates/jobs/apply_for_job.html
{% extends 'base.html' %}
{% block content %}
  
  <h1 class="title">{{ job.title }}</h1>
  <br>
  <h2 class="subtitle"><strong>Application</strong></h2>

  <form action="{% url 'apply_for_job' job.id %}" method="POST">
    {% csrf_token %}

    {% if form.errors %}
      {% for error in form.errors %}
        <div class="notification is-danger">
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}

    <div class="field">
      <label>Content</label>
      <div class="control">
        <textarea name="content" id="id_content" class="textarea"></textarea>
      </div>
    </div>
    
    <div class="field">
      <label>Experience</label>
      <div class="control">
        <textarea name="experience" id="id_experience" class="textarea"></textarea>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <button class="button">Submit</button>
      </div>
    </div>
  </form>
{% endblock content %}

templates/jobs/job.html
{% extends 'base.html' %} {% block content %}

<h1 class="title">{{ job.title }}</h1>

<p class="is-size-4">{{ job.description }}</p>
<p>{{ job.details }}</p>
<a href="{% url 'apply_for_job' job.id %}" class="button">Apply</a>

{% endblock content %}

templates/jobs/job_dashboard.html
{% extends 'base.html' %} {% block content %}

<h1 class="title">{{ job.title }}</h1>

{% for app in job.applications.all %}
  <a href="{% url 'application' app.id %}">{{ app.applicant.username }}</a>
{% endfor %}

{% endblock content %}

templates/jobs/new_job.html
{% extends 'base.html' %}
{% block content %}
  
  <h1 class="title">New job</h1>

  <form action="{% url 'new_job' %}" method="POST">
    {% csrf_token %}

    {% if form.errors %}
      {% for error in form.errors %}
        <div class="notification is-danger">
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}

    <div class="field">
      <label>Title</label>
      <div class="control">
        <input type="text" name="title" id="id_title">
      </div>
    </div>

    <div class="field">
      <label>Description</label>
      <div class="control">
        <textarea name="description" id="id_description" class="textarea"></textarea>
      </div>
    </div>
    
    <div class="field">
      <label>Detailed description</label>
      <div class="control">
        <textarea name="details" id="id_details" class="textarea"></textarea>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <button class="button">Submit</button>
      </div>
    </div>
  </form>
{% endblock content %}